#!/usr/bin/env python3
"""Append high-frequency Brazil investment guide entries to brazil_legal_corpus.json."""
from __future__ import annotations

import json
from pathlib import Path

CORPUS_PATH = Path(__file__).resolve().parents[1] / "backend/app/data/brazil_legal_corpus.json"

NEW_ENTRIES = [
    {
        "id": "lexml-lei-5709-terra-rural",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:1971-10-07;5709",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:1971-10-07;5709",
        "title_pt": "Lei nº 5.709/1971 - Aquisição de Imóvel Rural por Estrangeiros",
        "title_zh": "第5709/1971号法 — 外资农村土地取得限制",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "1971-10-07",
        "tags": ["terra", "rural", "INCRA", "土地", "外资", "农业"],
        "checklist_codes": ["FOR-002", "IND-001"],
        "text_pt": "Art. 3º - Sociedade com maioria de capital nacional (≥51% votos) não sofre restrições na aquisição de imóvel rural. Sociedade controlada por capital estrangeiro só pode adquirir imóvel rural para atividades agropecuárias, industriais ou de colonização compatíveis com seu objeto, sujeita a aprovação do Ministério da Agricultura e INCRA.",
        "text_zh": "第3条：巴西内资控股（表决权≥51%）合资企业购买土地无限制；外资控股企业（含100%外资）购买/租赁农村土地仅限从事农业、畜牧、工业或垦殖等经营范围活动，须农业部及 INCRA 审批；租赁与购买受同等限制。",
    },
    {
        "id": "lexml-lei-14286-cambio",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:2021-12-29;14286",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2021-12-29;14286",
        "title_pt": "Lei nº 14.286/2021 - Câmbio e Capitais Internacionais",
        "title_zh": "第14286/2021号法 — 外汇与国际资本法",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2021-12-29",
        "tags": ["câmbio", "BACEN", "real", "外汇", "雷亚尔", "RDE"],
        "checklist_codes": ["FOR-003"],
        "text_pt": "Moderniza o regime cambial brasileiro. O Real é moeda de curso forçado; câmbio deve ocorrer em mercados autorizados pelo Banco Central. Investimento estrangeiro direto exige registro declaratório eletrônico (RDE-IED) perante o BACEN, sem aprovação prévia na maioria dos casos.",
        "text_zh": "雷亚尔为巴西唯一流通货币；外汇须在央行批准场所按当日汇率兑换；外资主体须在巴西央行注册，一般仅需宣示性登记（Registro Declaratório），无需事先审批。",
    },
    {
        "id": "lexml-lei-13709-lgpd",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:2018-08-14;13709",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2018-08-14;13709",
        "title_pt": "Lei nº 13.709/2018 - LGPD",
        "title_zh": "第13709/2018号法 — 通用数据保护法 LGPD",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2018-08-14",
        "tags": ["LGPD", "ANPD", "dados", "数据保护", "隐私", "跨境传输"],
        "checklist_codes": ["FOR-002", "IND-004"],
        "text_pt": "Lei Geral de Proteção de Dados Pessoais. ANPD é autoridade reguladora. Dez bases legais incluem consentimento, obrigação legal, contrato, interesse legítimo e proteção ao crédito (base exclusiva brasileira). Transferência internacional exige adequação, cláusulas padrão (SCCs) ou garantias equivalentes. Multas até 2% da receita no Brasil, limitadas a R$ 50 milhões por infração.",
        "text_zh": "巴西首部综合性数据保护法；监管机构为 ANPD。合法性基础共十项，含独特的「信用保护」基础。跨境传输须充分性认定、标准合同条款（SCCs）等机制；违规罚款最高为巴西境内上一财年收入 2%，单次上限 5000 万雷亚尔。",
    },
    {
        "id": "lexml-lei-6938-politica-ambiental",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:1981-08-31;6938",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:1981-08-31;6938",
        "title_pt": "Lei nº 6.938/1981 - Política Nacional do Meio Ambiente",
        "title_zh": "第6938/1981号法 — 国家环境政策法",
        "dimension": "environment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "1981-08-31",
        "tags": ["SISNAMA", "IBAMA", "poluição", "环评", "环境政策"],
        "checklist_codes": ["ENV-001", "ENV-004"],
        "text_pt": "Estabelece o Sistema Nacional do Meio Ambiente (SISNAMA), instrumentos de licenciamento ambiental, EIA/RIMA para empreendimentos de significativo impacto, e responsabilidade civil por dano ambiental.",
        "text_zh": "建立国家环境系统，规定环境许可及重大环境影响项目的 EIA/RIMA 环评制度；污染者须承担环境修复及/或赔偿责任。",
    },
    {
        "id": "lexml-lei-9605-crimes-ambientais",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:1998-02-12;9605",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:1998-02-12;9605",
        "title_pt": "Lei nº 9.605/1998 - Crimes Ambientais",
        "title_zh": "第9605/1998号法 — 环境犯罪法",
        "dimension": "environment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "1998-02-12",
        "tags": ["crime", "ambiental", "licenciamento", "环境犯罪", "许可"],
        "checklist_codes": ["ENV-001", "ENV-004"],
        "text_pt": "Define como crime ambiental o dano resultante de descumprimento de normas de licenciamento ambiental e outras infrações contra o meio ambiente.",
        "text_zh": "将违反环境许可规定造成的环境损害定义为环境犯罪。",
    },
    {
        "id": "lexml-lei-9433-agua",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:1997-01-08;9433",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:1997-01-08;9433",
        "title_pt": "Lei nº 9.433/1997 - Política Nacional de Recursos Hídricos",
        "title_zh": "第9433/1997号法 — 国家水资源政策",
        "dimension": "environment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "1997-01-08",
        "tags": ["água", "recursos hídricos", "水资源", "取水许可"],
        "checklist_codes": ["ENV-001", "ENV-004"],
        "text_pt": "Estabelece que qualquer uso de recursos hídricos deve ser aprovado pelas autoridades competentes.",
        "text_zh": "规定任何水资源利用均须获得公共主管机关批准。",
    },
    {
        "id": "lexml-lei-12651-codigo-florestal",
        "source": "lexml",
        "urn": "urn:lex:br:federal:lei:2012-05-25;12651",
        "url": "https://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2012-05-25;12651",
        "title_pt": "Lei nº 12.651/2012 - Código Florestal",
        "title_zh": "第12651/2012号法 — 林业法（森林法典）",
        "dimension": "environment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2012-05-25",
        "tags": ["floresta", "Amazônia", "APP", "森林", "保护区"],
        "checklist_codes": ["ENV-001", "ENV-002"],
        "text_pt": "Regulamenta proteção e uso sustentável de recursos florestais, áreas de preservação permanente (APP), reservas legais e manejo de áreas protegidas incluindo Amazônia.",
        "text_zh": "详细规定林业资源保护利用、永久 preservation 区、法定保留地及亚马逊等保护区管理。",
    },
    {
        "id": "lexml-const-art-222-midia",
        "source": "lexml",
        "urn": "urn:lex:br:federal:constituicao:1988;222",
        "url": "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
        "title_pt": "Constituição Art. 222 - Comunicação Social",
        "title_zh": "宪法第222条 — 大众传媒外资限制",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "1988-10-05",
        "tags": ["mídia", "radiodifusão", "49%", "传媒", "广播", "外资限制"],
        "checklist_codes": ["FOR-002"],
        "text_pt": "Empresa jornalística e de radiodifusão sonora e de imagem: capital votante e capital total com no mínimo 70% pertencente a brasileiros natos ou naturalizados há mais de 10 anos. Serviços de telecomunicação não broadcast: limite de 49% capital estrangeiro, salvo alterações legislativas posteriores.",
        "text_zh": "报刊及音像广播公司：总资本及表决权资本至少70%须由在巴西出生或入籍满10年的巴西公民持有。非广播电信服务外资持股通常不超过49%，特定情形须政府审批。",
    },
    {
        "id": "lexml-const-art-199-saude",
        "source": "lexml",
        "urn": "urn:lex:br:federal:constituicao:1988;199",
        "url": "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
        "title_pt": "Constituição Art. 199 - Saúde e Capital Estrangeiro",
        "title_zh": "宪法第199条 — 医疗保健外资限制",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "1988-10-05",
        "tags": ["saúde", "ANVISA", "医疗", "外资禁止"],
        "checklist_codes": ["FOR-002"],
        "text_pt": "Instituições privadas de assistência à saúde: capital estrangeiro é vedado, salvo exceções para entidades filantrópicas, sem fins lucrativos ou hospitais que atendam critérios de desenvolvimento tecnológico definidos em lei.",
        "text_zh": "私营医疗保健机构原则上禁止外国资本参与，慈善、非营利或符合特定技术发展标准的医院除外。",
    },
    {
        "id": "jusbrasil-guide-fdi-overview",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-fdi-overview",
        "url": "https://apexbrasil.com.br/",
        "title_pt": "Guia de Investimento — Ambiente Jurídico e Acesso de Capital Estrangeiro",
        "title_zh": "投资指南 — 巴西投资法律环境概览及外资准入",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["PPI", "APEX", "BNDES", "4131", "国民待遇", "外资"],
        "checklist_codes": ["FOR-001", "FOR-002", "FOR-003"],
        "text_pt": "Lei 4.131/1962 e Decreto 55.762/1965 regem investimento estrangeiro com tratamento nacional. PPI (2016) coordena privatizações e infraestrutura. APEX-Brasil e BNDES apoiam investidores. Entrada de capital via RDE-IED no BACEN; câmbio em mercados autorizados.",
        "text_zh": "《外资法》（Lei 4131/1962）及施行细则为外商投资监管基础；外商独资或合资享受国民待遇。2016 年起 PPI（投资伙伴计划）协调基础设施采购与私有化，承诺不国有化。主管机构含 APEX-Brasil（投资促进）与 BNDES（项目融资）。外汇须在央行批准场所兑换；外资一般仅需央行宣示性登记。",
    },
    {
        "id": "jusbrasil-guide-fdi-restricted-sectors",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-fdi-restrictions",
        "url": "https://www.gov.br/produtividade-e-comercio-exterior/pt-br",
        "title_pt": "Guia — Setores com Restrição ou Vedação ao Capital Estrangeiro",
        "title_zh": "投资指南 — 外资禁止/限制行业清单",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["核", "土地", "医疗", "传媒", "金融", "国防", "准入限制"],
        "checklist_codes": ["FOR-002"],
        "text_pt": "Restrições principais: (1) energia nuclear e minerais estratégicos — monopólio estatal; (2) imóvel rural — Lei 5.709/1971; (3) saúde privada — Art. 199 CF; (4) mídia/radiodifusão — Art. 222 CF (70% capital nacional); (5) instituições financeiras — aprovação prévia BACEN; (6) defesa/aeroespacial/naval costeiro — aprovação especial; (7) importação: produtos de origem animal (MAPA), farmacêuticos (ANVISA), padrões técnicos (INMETRO).",
        "text_zh": "主要限制领域：（1）核能及战略矿物 — 国家垄断；（2）农村土地 — Lei 5709/1971；（3）私营医疗 — 宪法第199条；（4）新闻广播 — 宪法第222条（70% 本国资本）；（5）金融机构 — 须央行事先批准；（6）航空航天/国防/沿海航运 — 专项批准；（7）进口管制：动物源性产品（农业部）、医药卫生产品（ANVISA）、技术标准（INMETRO）。",
    },
    {
        "id": "jusbrasil-guide-company-setup",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-company-formation",
        "url": "https://www.gov.br/empresas-e-negocios/pt-br",
        "title_pt": "Guia — Constituição de Sociedade Limitada (LTDA) por Investidor Estrangeiro",
        "title_zh": "投资指南 — 外商投资企业设立（有限责任公司）",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["LTDA", "CNPJ", "NIRE", "股东会", "设立", "RedeSim"],
        "checklist_codes": ["FOR-001"],
        "text_pt": "Formas comuns: LTDA e S/A; filial e representação sem personalidade jurídica. LTDA: mínimo 2 sócios, capital em Reais, pagamento mínimo 10% na constituição, saldo em até 5 anos. Governança obrigatória: Reunião de Sócios e Administração. Sócio estrangeiro precisa procurador residente no Brasil para atas. Fluxo: reserva de nome, estatuto/contrato social, registro Junta Comercial, CNPJ, registro municipal, INSS, conta bancária, RDE-IED.",
        "text_zh": "常见形式：有限责任公司（LTDA）与股份有限公司（S/A）；分支机构/代表处无独立法人资格。LTDA 须两人以上出资，资本以雷亚尔计，设立时至少缴纳10%、余款最长五年缴清。必设股东会与管理层的双层治理；外国股东作决议须由巴西境内代理人签署。设立流程：核名 → 章程公证 → 商业登记（NIRE/CNPJ）→ 市政登记 → 社保登记 → 银行开户 → 外资 RDE-IED 登记。全国 RedeSim 网络整合联邦/州/市审批。",
    },
    {
        "id": "jusbrasil-guide-land-lease",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-land-foreign",
        "url": "https://www.gov.br/incra/pt-br",
        "title_pt": "Guia — Aquisição e Locação de Imóvel Rural por Estrangeiros",
        "title_zh": "投资指南 — 外资土地取得/租赁",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["INCRA", "5709", "MODULO", "租赁", "8245", "优先购买权"],
        "checklist_codes": ["FOR-002", "IND-001"],
        "text_pt": "Lei 5.709/1971: empresa ≥51% capital nacional — sem limite; controlada por estrangeiros — restrições de área (módulos) e finalidade agro/industrial. Aprovação MAPA + INCRA. Lei 8.245/91 (locação urbana): venda durante locação — comprador pode rescindir com 90 dias se contrato não registrado; locatário tem direito de preferência se registro ≥30 dias.",
        "text_zh": "Lei 5709/1971：内资控股≥51% 无土地购买限制；外资控股企业购买/租赁农村土地受限，须农业部及 INCRA 审批，面积以「模」（MODULO，约5–100公顷/模，依区域而定）计量。城市租赁法 Lei 8245/91：租赁期内出售 — 未登记租赁协议时买方可提前90天通知终止；承租人享有优先购买权（租赁协议须提前30天登记）。",
    },
    {
        "id": "jusbrasil-guide-labor-core",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-labor-practices",
        "url": "https://www.gov.br/trabalho-e-emprego/pt-br",
        "title_pt": "Guia — Regime Trabalhista Brasileiro (CLT)",
        "title_zh": "投资指南 — 巴西劳动用工基本制度",
        "dimension": "labor",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["CLT", "13467", "13º", "FGTS", "44h", "工会", "解雇"],
        "checklist_codes": ["LAB-001", "LAB-002", "LAB-003"],
        "text_pt": "CLT (Decreto-Lei 5452/1943, reforma Lei 13.467/2017): 8h/dia, 44h/semana; hora extra 150%; feriado 200%; noturno 120%. 13º salário; 30 dias férias após 12 meses (+1/3). FGTS 8% mensal. INSS: empregador ~20% + acidente; empregado 7,5–14%. Proporção mínima 2/3 trabalhadores e folha brasileiros. Demissão sem justa causa: aviso 30 dias, FGTS + multa 40%.",
        "text_zh": "《统一劳工法》CLT（2017改革生效）：日8小时/周44小时；加班150%、节假日200%、夜班120%。第13薪；满1年30天带薪年假（可分段，每段≥5天）。FGTS 雇主每月缴存8%。社保：雇主约20%+工伤基金；雇员7.5%–14%。本地员工人数及工资须各≥总数/总额的2/3。无正当理由解雇：30天通知、FGTS全额+40%罚金；协商解除 FGTS 罚金20%。工会力量强，集体合同（CCT）可高于法定标准。",
    },
    {
        "id": "jusbrasil-guide-foreign-worker",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-foreign-worker",
        "url": "https://www.gov.br/mj/pt-br/assuntos/migracao",
        "title_pt": "Guia — Trabalhador Estrangeiro: Permissão e Visto",
        "title_zh": "投资指南 — 外国人在巴西工作规定",
        "dimension": "labor",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["visto", "work permit", "CPF", "INSS", "外派", "2/3"],
        "checklist_codes": ["LAB-004"],
        "text_pt": "Pré-requisitos: habilidade técnica, autorização de trabalho (MJ/Immigração online), visto de trabalho (1–2 anos, renovável). Superior: ≥2 anos experiência; médio: ≥3 anos. Documentos: contrato padrão, comprovantes INSS/FGTS/IR, diplomas apostilados. Empregador obtém CPF e INSS do estrangeiro. Proporção 2/3 brasileiros na prática muito inferior ao teto legal 1/3.",
        "text_zh": "外籍员工须具备专业技能、工作许可及工作签证三项前提。高学历者至少2年专业经验，中等学历至少3年。企业向司法部移民局在线申请工作许可，提交固定格式申请表、公证学历、公司章程、最近 INSS/FGTS/所得税缴纳证明及劳务合同。获批后外交部通知驻外使领馆签发工作签证（有效期通常1–2年）。雇主须为其办理 CPF 及 INSS 登记。法定外籍比例上限1/3，实践中获批比例通常更低。",
    },
    {
        "id": "jusbrasil-guide-tax-system",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-tax-overview",
        "url": "https://www.gov.br/receitafederal/pt-br",
        "title_pt": "Guia — Sistema Tributário Brasileiro para Investidores",
        "title_zh": "投资指南 — 巴西税收体系概览",
        "dimension": "tax",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["IRPJ", "CSLL", "ICMS", "IPI", "PIS", "COFINS", "ISS", "关税", "90税种"],
        "checklist_codes": ["TAX-001", "TAX-002", "TAX-003", "TAX-004"],
        "text_pt": "Sistema constitucional tripartite (União, Estados, Municípios), >90 tributos. IRPJ/CSLL: 15% + adicional 10% sobre lucro >R$240mil/ano; CSLL 9%; Lucro Real/Presumido/Simples. ICMS estadual 17–20% intraestado, 4–12% interestadual. IPI 0–55%. PIS/COFINS cumulativo 0,65%/3% ou não-cumulativo 1,65%/7,6%. ISS municipal 2–5%. Importação: II 0–35% + IPI + ICMS + PIS/COFINS. IOF redução gradual até 0% em 2028.",
        "text_zh": "宪政三级税制（联邦/州/市），税种超过90种。企业所得税 IRPJ 15%+超额10%附加（年利润超24万雷亚尔），CSLL 9%；适用实际利润/假定利润/简易税制。ICMS 州内17%–20%、州际4%–12%；IPI 0%–55%；PIS/COFINS 累计制0.65%/3%或非累计制1.65%/7.6%；ISS 市级2%–5%。进口关税0%–35%，另加 IPI、ICMS、PIS/COFINS 及清关杂费。IOF 自2023年起逐步减至2028年归零。",
    },
    {
        "id": "jusbrasil-guide-lgpd-practice",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-lgpd-practice",
        "url": "https://www.gov.br/anpd/pt-br",
        "title_pt": "Guia — LGPD: Obrigações e Diferenças em Relação ao GDPR",
        "title_zh": "投资指南 — LGPD 合规要点及与 GDPR 对比",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["LGPD", "ANPD", "DPO", "SCC", "Resolução 19/2024", "数据跨境"],
        "checklist_codes": ["FOR-002", "IND-004"],
        "text_pt": "ANPD: autoridade única federal. 10 bases legais incluindo proteção ao crédito. DPO obrigatório para controladores (não operadores); pequenos agentes dispensados. Transferência internacional: Resolução CD/ANPD 19/2024 — SCCs até 23/08/2025; adequação ainda sem países listados. Notificação incidentes: prazo 'razoável' (Res. 15/2024). Multas até 2% receita Brasil, teto R$50mi. Diferente GDPR: sem pena criminal; DPO só controlador.",
        "text_zh": "ANPD 为联邦统一监管机构。十项合法性基础含「信用保护」。控制者须任命 DPO（处理者自愿）；小微主体可豁免。2024年 Resolução 19/2024 细化跨境传输，标准合同条款（SCCs）须于2025年8月23日前过渡；尚无大规模充分性认定，实践以 SCCs 为主。泄露通报为「合理期限」（Res. 15/2024），非 GDPR 72 小时。罚款上限为巴西境内收入2%或5000万雷亚尔/次。与 GDPR 差异：无刑事处罚；DPO 仅控制者强制。",
    },
    {
        "id": "jusbrasil-guide-import-export",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-trade-compliance",
        "url": "https://www.gov.br/produtividade-e-comercio-exterior/pt-br/assuntos/camex",
        "title_pt": "Guia — Comércio Exterior, Licenças e SISCOMEX",
        "title_zh": "投资指南 — 进出口管制与贸易合规",
        "dimension": "industry_access",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["SISCOMEX", "Radar", "LI", "CAMEX", "进口许可", "出口"],
        "checklist_codes": ["TAX-004", "IND-002", "ENV-003"],
        "text_pt": "CAMEX define política comercial. Importação: maioria exige LI (automática ou não-automática) via Siscomex antes do embarque. Radar (Receita Federal): licença obrigatória import/export. Registro SISCOMEX para despacho aduaneiro. ANVISA: produtos farmacêuticos/saúde. MAPA: produtos de origem animal. INMETRO: normas técnicas. Impostos na importação: II + IPI + ICMS + PIS/COFINS + taxas portuárias.",
        "text_zh": "对外贸易委员会 CAMEX 为最高决策机构。大部分进口须装船前在 Siscomex 申请自动/非自动进口许可证（LI）。Radar 许可证（联邦税务局）为进出口必备；所有清关须通过 SISCOMEX 登记。医药卫生产品须 ANVISA 批准；动物源性产品须农业部检验局批准；技术标准由 INMETRO 制定。进口环节税金含关税、IPI、PIS/COFINS、ICMS 及港口杂费（含商船队附加费约为海运费25%）。",
    },
    {
        "id": "jusbrasil-guide-industry-licenses",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-industry-licenses",
        "url": "https://www.gov.br/anvisa/pt-br",
        "title_pt": "Guia — Licenças Setoriais (ANVISA, Radar, INPI)",
        "title_zh": "投资指南 — 行业准入证照（医疗器械/Radar/SISCOMEX）",
        "dimension": "industry_access",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["ANVISA", "Radar", "INMETRO", "医疗器械", "III类", "IV类"],
        "checklist_codes": ["IND-002", "IND-006", "TAX-004"],
        "text_pt": "Dispositivos médicos ANVISA: Classes III e IV exigem registro + certificado BPF/GMP; representante local brasileiro obrigatório. Radar: licença Receita Federal import/export. SISCOMEX: registro aduaneiro. INMETRO: certificação compulsória produtos industrializados incluindo veículos elétricos.",
        "text_zh": "医疗器械按风险分 I–IV 类；III/IV 类须 ANVISA 注册及巴西 GMP 体系证书，须指定巴西本地代表（仅本地公司可提交注册）。Radar 许可证为进出口必备（联邦税务局颁发）。SISCOMEX 为海关进出口登记系统。INMETRO 负责强制性产品标准与合格评定（含电动车辆）。",
    },
    {
        "id": "jusbrasil-guide-ip-system",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-ip-system",
        "url": "https://www.gov.br/inpi/pt-br",
        "title_pt": "Guia — Propriedade Intelectual (INPI): Marcas, Patentes e Direitos Autorais",
        "title_zh": "投资指南 — 巴西知识产权制度（商标/专利/著作权）",
        "dimension": "industry_access",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["INPI", "Madrid", "Paris", "PCT", "商标", "专利", "14200"],
        "checklist_codes": ["IND-004", "FOR-004"],
        "text_pt": "Base legal: Lei 14.200/2021 (PI), Lei 9.610/1998 (autoral). Marcas INPI/Madrid: oposição 60 dias, registro ~10–12 meses, validade 10 anos. Patentes: invenção 20 anos, modelo utilidade 15 anos; exame substantivo requerido em 36 meses; ciclo médio ~11 anos; PPH/green patents fast track. ANVISA pré-autorização para patentes farmacêuticas. Direitos autorais: vida autor + 70 anos.",
        "text_zh": "法律依据：《工业产权法》Lei 14200/2021、《著作权法》Lei 9610/1998；巴西为马德里体系及巴黎公约/PCT 缔约国。商标：向 INPI 或马德里体系申请，须葡萄牙语；公告异议期60天，注册周期约10–12个月，保护期10年。专利：发明20年、实用新型15年（中国实用新型10年）；须36个月内请求实质审查；平均注册约11年，可走 PPH/绿色专利加速。药品专利须 ANVISA 事先同意。著作权：作者终身+死后70年（中国为50年）。",
    },
    {
        "id": "jusbrasil-guide-env-licensing",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-env-licensing-steps",
        "url": "https://www.gov.br/ibama/pt-br",
        "title_pt": "Guia — Licenciamento Ambiental em Três Fases",
        "title_zh": "投资指南 — 巴西环评三阶段许可",
        "dimension": "environment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["EIA", "LP", "LI", "LO", "IBAMA", "三阶段", "环评"],
        "checklist_codes": ["ENV-001", "ENV-004"],
        "text_pt": "Empreendimentos estrangeiros exigem avaliação de impacto ambiental. Três etapas: (1) Licença Prévia (LP) — planejamento, localização e viabilidade; (2) Licença de Instalação (LI) — plano básico ambiental, autoriza obras; (3) Licença de Operação (LO) — plano ambiental detalhado, autoriza operação. MMA/IBAMA e órgãos estaduais executam.",
        "text_zh": "外资投资或承包工程须完成环境影响评估。环评三步骤：（1）初步许可（LP）— 规划阶段，批准工程位置、环境可行性及技术方案，尚不能开工；（2）开工许可（LI）— 提交基础环境计划，审核通过后方可开工建设；（3）施工/运营许可（LO）— 提交详细环境计划及前述方案，批准后方可运营。环境和气候变化部及 IBAMA/州环境厅主管。",
    },
    {
        "id": "jusbrasil-guide-cade-ma",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-cade-ma",
        "url": "https://www.gov.br/cade/pt-br",
        "title_pt": "Guia — CADE: Controle de Concentrações e Due Diligence",
        "title_zh": "投资指南 — CADE 反垄断申报及并购尽调",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["CADE", "12529", "并购", "7.5亿", "7500万", "尽调"],
        "checklist_codes": ["FOR-005", "FOR-002"],
        "text_pt": "Lei 12.529/2011: notificação obrigatória se um grupo faturamento Brasil ≥R$750mi E outro ≥R$75mi, ou se operação criar participação ≥20% mercado relevante. Procedimento sumário ~60 dias; ordinário ~90 dias, prazo máximo 240 dias. Multa não notificação: R$60mil–R$60mi. Due diligence: documentos societários, contratos comerciais/financeiros, IP, LGPD, imóveis (restrição terra rural estrangeiros), litígios, tributário, trabalhista, ambiental, anticorrupção/CADE.",
        "text_zh": "Lei 12529/2011：任一参与方在巴西年营收≥7.5亿雷亚尔且另一方≥7500万雷亚尔，须交割前向 CADE 申报；未申报可无效且罚款6万–6000万雷亚尔。简易程序约60自然日，普通程序约90日，最长240日。并购尽调重点：公司文件、商业/财务协议、银行业务（央行外汇合规）、知识产权、LGPD 数据保护、不动产（外资农村土地限制）、诉讼仲裁、税务、劳动用工、环境、反腐败/反垄断（CADE）。",
    },
    {
        "id": "jusbrasil-guide-ma-structure",
        "source": "jusbrasil",
        "urn": "jusbrasil:guide:brazil-ma-structure",
        "url": "https://www.gov.br/cade/pt-br",
        "title_pt": "Guia — Estruturação de M&A no Brasil (Equity vs Ativos)",
        "title_zh": "投资指南 — 巴西并购交易结构（股权 vs 资产）",
        "dimension": "foreign_investment",
        "level": "federal",
        "validity": "vigente",
        "published_at": "2025-01-01",
        "tags": ["股权收购", "资产收购", "CLT 448", "税收历史", "劳动债务"],
        "checklist_codes": ["FOR-005", "FOR-004"],
        "text_pt": "Aquisição de quotas/ações: sem ICMS/IPI/PIS-COFINS na transferência; comprador assume passivos fiscais e trabalhistas históricos (CLT arts. 10 e 448 — emprego continua automaticamente). Aquisição de ativos: incide tributos sobre bens; empregados só transferem com consentimento; passivo trabalhista limitado aos aceitos. Setores regulados (telecom ANATEL >20% estrangeiro, petróleo ANP, energia ANEEL) exigem aprovação setorial paralela ao CADE.",
        "text_zh": "股权收购：通常不触发 ICMS/IPI/PIS-COFINS 流转税；买方可继承 tax loss、税收优惠等税收属性，但须承继全部历史劳动债务（CLT 第10/448条 — 雇佣关系自动延续）。资产收购：各资产类别分别计税，员工转移须本人同意，劳动风险可隔离。电信（ANATEL，外资>20%须单独审批）、石油天然气（ANP）、电力（ANEEL）等特许/授权行业，行业前置审批与 CADE 反垄断审查并行独立。",
    },
]


def main() -> None:
    with open(CORPUS_PATH, encoding="utf-8") as f:
        corpus = json.load(f)

    existing_ids = {s["id"] for s in corpus["sources"]}
    added = 0
    for entry in NEW_ENTRIES:
        if entry["id"] in existing_ids:
            print(f"skip existing: {entry['id']}")
            continue
        corpus["sources"].append(entry)
        existing_ids.add(entry["id"])
        added += 1

    parts = str(corpus.get("version", "1.3")).split(".")
    if len(parts) >= 2 and parts[-1].isdigit():
        parts[-1] = str(int(parts[-1]) + 1)
    corpus["version"] = ".".join(parts)

    with open(CORPUS_PATH, "w", encoding="utf-8") as f:
        json.dump(corpus, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Added {added} entries; corpus version {corpus['version']}; total {len(corpus['sources'])} docs")


if __name__ == "__main__":
    main()
